name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ inputs.service_name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.34

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Lint & format check
        run: |
          bun run lint
          bun run format:check

      - name: Type checking
        run: bun run ts-check

      - name: Dependency Checking
        run: bun run knip